name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: cd PokeLib-Frontend && npm install

      - name: Create frontend .env
        run: |
          echo "VITE_API_URL=https://api-pokelib.barouth.fr/api" > PokeLib-Frontend/.env
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> PokeLib-Frontend/.env
          echo "VITE_GOOGLE_CLIENT_SCOPE='https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'" >> PokeLib-Frontend/.env

      - name: Build frontend
        run: cd PokeLib-Frontend && npm run build

      - name: Install backend dependencies
        run: cd PokeLib-Backend && npm install

      - name: Create backend .env
        run: |
          echo "DATABASE_URL=${{ secrets.BACKEND_DATABASE_URL }}" > PokeLib-Backend/.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> PokeLib-Backend/.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> PokeLib-Backend/.env
          echo "GOOGLE_REDIRECT_URI=https://pokelib.barouth.fr" >> PokeLib-Backend/.env
          echo "JWT_SECRET=${{ secrets.BACKEND_JWT_SECRET }}" >> PokeLib-Backend/.env
          echo "JWT_EXPIRES_IN=1d" >> PokeLib-Backend/.env

      - name: Apply all pending migrations to the database
        run: cd PokeLib-Backend && npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.REMOTE_DATABASE_URL }}
          
      - name: Build backend
        run: cd PokeLib-Backend && npm run build

      - name: Deploy artifacts
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "PokeLib-Backend/dist/*, PokeLib-Frontend/dist/*"
          target: /var/www/html/
