name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: cd Pokelib-Frontend && npm install

      - name: Build frontend
        run: cd Pokelib-Frontend && npm run build

      - name: Install backend dependencies
        run: cd Pokelib-Backend && npm install

      - name: Build backend
        run: cd Pokelib-Backend && npm run build

      - name: Deploy artifacts
        uses: appleboy/scp-action@v2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: |
            Pokelib-Frontend/dist/
            Pokelib-Backend/dist/
          target: /var/www/html
